version: '3'

services: 
    rest_api:
        container_name: flask_scratch_rest_api
        build: .
        volumes: 
            - .:/code
        ports: 
            - "5000:5000"
        depends_on: 
            - db
        stdin_open: true
        tty: true
        restart: unless-stopped
    db:
        image: postgres
        container_name: flask_scratch_rest_api_db
        environment:
            POSTGRES_DB: "flask-scratch"
            POSTGRES_USER: "flask"
            POSTGRES_HOSTNAME: "localhost"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes: 
    pgdata: