"""add blacklist table

Revision ID: 678a65195802
Revises: 1cea610bb48b
Create Date: 2020-10-05 09:35:30.524524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678a65195802'
down_revision = '1cea610bb48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
